import type { KeyBinding } from "./types";

export const DEFAULT_BINDINGS: KeyBinding[] = [
  { id: "any.pop", scope: "any", key: "`", label: "Go back one mode" },
  { id: "any.close", scope: "any", key: "Escape", label: "Close Figmode" },
  {
    id: "any.settings",
    scope: "any",
    key: "Shift+s",
    label: "Open settings",
  },
  { id: "layout.flow.row", scope: "layout", key: "r", label: "Row flow" },
  {
    id: "layout.flow.column",
    scope: "layout",
    key: "c",
    label: "Column flow",
  },
  {
    id: "layout.flow.freeform",
    scope: "layout",
    key: "f",
    label: "Freeform (remove auto layout)",
  },
  { id: "layout.flow.grid", scope: "layout", key: "g", label: "Grid flow" },
  {
    id: "layout.submode.width",
    scope: "layout",
    key: "w",
    label: "Width sizing",
  },
  {
    id: "layout.submode.height",
    scope: "layout",
    key: "h",
    label: "Height sizing",
  },
  {
    id: "layout.submode.alignment",
    scope: "layout",
    key: "a",
    label: "Alignment",
  },
  {
    id: "layout.submode.spacing",
    scope: "layout",
    key: "s",
    label: "Spacing & padding",
  },
  {
    id: "layout.wrap.toggle",
    scope: "layout",
    key: "e",
    label: "Toggle flow wrap",
  },
  {
    id: "layout.width.fixed",
    scope: "layout.width",
    key: "a",
    label: "Fixed width",
  },
  {
    id: "layout.width.hug",
    scope: "layout.width",
    key: "s",
    label: "Hug contents width",
  },
  {
    id: "layout.width.fill",
    scope: "layout.width",
    key: "d",
    label: "Fill container width",
  },
  {
    id: "layout.height.fixed",
    scope: "layout.height",
    key: "a",
    label: "Fixed height",
  },
  {
    id: "layout.height.hug",
    scope: "layout.height",
    key: "s",
    label: "Hug contents height",
  },
  {
    id: "layout.height.fill",
    scope: "layout.height",
    key: "d",
    label: "Fill container height",
  },
  {
    id: "layout.alignment.topLeft",
    scope: "layout.alignment",
    key: "q",
    label: "Align top-left",
  },
  {
    id: "layout.alignment.topCenter",
    scope: "layout.alignment",
    key: "w",
    label: "Align top-center",
  },
  {
    id: "layout.alignment.topRight",
    scope: "layout.alignment",
    key: "e",
    label: "Align top-right",
  },
  {
    id: "layout.alignment.middleLeft",
    scope: "layout.alignment",
    key: "a",
    label: "Align middle-left",
  },
  {
    id: "layout.alignment.middleCenter",
    scope: "layout.alignment",
    key: "s",
    label: "Align center",
  },
  {
    id: "layout.alignment.middleRight",
    scope: "layout.alignment",
    key: "d",
    label: "Align middle-right",
  },
  {
    id: "layout.alignment.bottomLeft",
    scope: "layout.alignment",
    key: "z",
    label: "Align bottom-left",
  },
  {
    id: "layout.alignment.bottomCenter",
    scope: "layout.alignment",
    key: "x",
    label: "Align bottom-center",
  },
  {
    id: "layout.alignment.bottomRight",
    scope: "layout.alignment",
    key: "c",
    label: "Align bottom-right",
  },
  {
    id: "layout.spacing.gapToggle",
    scope: "layout.spacing",
    key: "f",
    label: "Toggle auto / px gap",
  },
  {
    id: "layout.spacing.paddingTop",
    scope: "layout.spacing",
    key: "w",
    label: "Padding top",
  },
  {
    id: "layout.spacing.paddingLeft",
    scope: "layout.spacing",
    key: "a",
    label: "Padding left",
  },
  {
    id: "layout.spacing.paddingRight",
    scope: "layout.spacing",
    key: "d",
    label: "Padding right",
  },
  {
    id: "layout.spacing.paddingBottom",
    scope: "layout.spacing",
    key: "x",
    label: "Padding bottom",
  },
  {
    id: "layout.spacing.paddingX",
    scope: "layout.spacing",
    key: "q",
    label: "Padding horizontal",
  },
  {
    id: "layout.spacing.paddingY",
    scope: "layout.spacing",
    key: "e",
    label: "Padding vertical",
  },
];
