import type { KeyBinding } from "./types";

export const DEFAULT_BINDINGS: KeyBinding[] = [
  { id: "any.pop", scope: "any", key: "`", label: "Back" },
  { id: "any.close", scope: "any", key: "Escape", label: "Quit" },
  {
    id: "any.settings",
    scope: "any",
    key: "Shift+s",
    label: "Open settings",
  },
  {
    id: "layout.flow.freeform",
    scope: "layout",
    key: "f",
    label: "Set freeform flow",
  },
  {
    id: "layout.flow.column",
    scope: "layout",
    key: "c",
    label: "Set column flow",
  },
  { id: "layout.flow.row", scope: "layout", key: "r", label: "Set row flow" },
  { id: "layout.flow.grid", scope: "layout", key: "g", label: "Set grid flow" },
  {
    id: "layout.wrap.toggle",
    scope: "layout",
    key: "e",
    label: "Toggle wrap",
  },
  {
    id: "layout.submode.width",
    scope: "layout",
    key: "w",
    label: "Width",
  },
  {
    id: "layout.submode.height",
    scope: "layout",
    key: "h",
    label: "Height",
  },
  {
    id: "layout.submode.alignment",
    scope: "layout",
    key: "a",
    label: "Alignment",
  },
  {
    id: "layout.submode.spacing",
    scope: "layout",
    key: "s",
    label: "Spacing",
  },
  {
    id: "layout.submode.padding",
    scope: "layout",
    key: "p",
    label: "Padding",
  },
  {
    id: "layout.width.fixed",
    scope: "layout.width",
    key: "a",
    label: "Fixed width",
  },
  {
    id: "layout.width.hug",
    scope: "layout.width",
    key: "s",
    label: "Hug contents",
  },
  {
    id: "layout.width.fill",
    scope: "layout.width",
    key: "d",
    label: "Fill container",
  },
  {
    id: "layout.height.fixed",
    scope: "layout.height",
    key: "a",
    label: "Fixed height",
  },
  {
    id: "layout.height.hug",
    scope: "layout.height",
    key: "s",
    label: "Hug contents",
  },
  {
    id: "layout.height.fill",
    scope: "layout.height",
    key: "d",
    label: "Fill container",
  },
  {
    id: "layout.alignment.topLeft",
    scope: "layout.alignment",
    key: "q",
    label: "Top-Left",
  },
  {
    id: "layout.alignment.topCenter",
    scope: "layout.alignment",
    key: "w",
    label: "Top",
  },
  {
    id: "layout.alignment.topRight",
    scope: "layout.alignment",
    key: "e",
    label: "Top-Right",
  },
  {
    id: "layout.alignment.middleLeft",
    scope: "layout.alignment",
    key: "a",
    label: "Left",
  },
  {
    id: "layout.alignment.middleCenter",
    scope: "layout.alignment",
    key: "s",
    label: "Center",
  },
  {
    id: "layout.alignment.middleRight",
    scope: "layout.alignment",
    key: "d",
    label: "Right",
  },
  {
    id: "layout.alignment.bottomLeft",
    scope: "layout.alignment",
    key: "z",
    label: "Lower-Left",
  },
  {
    id: "layout.alignment.bottomCenter",
    scope: "layout.alignment",
    key: "x",
    label: "Bottom",
  },
  {
    id: "layout.alignment.bottomRight",
    scope: "layout.alignment",
    key: "c",
    label: "Lower-Right",
  },
  {
    id: "layout.spacing.gapToggle",
    scope: "layout.spacing",
    key: "f",
    label: "Toggle auto / fixed gap",
  },
  {
    id: "layout.padding.all",
    scope: "layout.padding",
    key: "s",
    label: "All",
  },
  {
    id: "layout.padding.paddingTop",
    scope: "layout.padding",
    key: "w",
    label: "Top",
  },
  {
    id: "layout.padding.paddingLeft",
    scope: "layout.padding",
    key: "a",
    label: "Left",
  },
  {
    id: "layout.padding.paddingRight",
    scope: "layout.padding",
    key: "d",
    label: "Right",
  },
  {
    id: "layout.padding.paddingBottom",
    scope: "layout.padding",
    key: "x",
    label: "Bottom",
  },
  {
    id: "layout.padding.paddingX",
    scope: "layout.padding",
    key: "q",
    label: "Horizontal",
  },
  {
    id: "layout.padding.paddingY",
    scope: "layout.padding",
    key: "e",
    label: "Vertical",
  },
];
